config/routes.rb
Rails.application.routes.draw do
	
  resources :user_appraisals
  root 'user_appraisals#index'
  get '/my_appraisals'  => 'user_appraisals#my_appraisals'
  get '/user_appraisal/:user_id'  => 'user_appraisals#user_appraisal'
  #devise routes
  devise_for :users, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :user_appraisals
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :appraisee, class_name: 'User'
  belongs_to :appraiser, class_name: 'User' #current_user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
	has_many :user_appraisals   
end

app/models/user_appraisal.rb
class UserAppraisal < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :transactions

  validates :comment, presence: true
  validates :points, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/user_appraisals_controller.rb
class UserAppraisalsController < ApplicationController
  before_action :set_appraisal, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  def index
    @users = User.where.not(id: current_user)
    @categories = Category.all
  end

  def my_appraisals
    @user_appraisals = current_user.user_appraisals
  end

  def new
    @user_appraisal = UserAppraisal.new
  end

  def user_appraisal
    return redirect_to user_appraisals_url, alert: "You are not authorised to perform this action" unless current_user.manager?
    @user = User.find(params[:user_id])
    @user_appraisals = @user.user_appraisals
  end

  def create
    @user_appraisal = UserAppraisal.new(appraisal_params)
    if current_user.points >= appraisal_params[:points].to_i && @user_appraisal.save
      complete_transaction
      redirect_to user_appraisals_url
    else
      flash[:notice] = "Points exhausted, should be less than #{current_user.points} !"
      redirect_to user_appraisals_url
    end
  end

  def update
    if @user_appraisal.update(appraisal_params)
			redirect_to @appraisal, notice: 'appraisal was successfully updated.'
    end
  end

  def destroy
    @user_appraisal.destroy
    redirect_to user_appraisals_url, notice: 'Appraisal was successfully destroyed.'
  end

	private
  def set_appraisal
    @user_appraisal = Appraisal.find(params[:id])
  end

  def complete_transaction
    Transaction.create(appraisee: @user_appraisal.user, appraiser: current_user, category: @user_appraisal.category)
    current_user.update points: (current_user.points - appraisal_params[:points].to_i)
  end

  def appraisal_params
    params.require(:user_appraisal).permit(:user_id, :category_id, :comment, :points)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_appraisals_helper.rb
module UserAppraisalsHelper
end

app/views/categories/_category.html.erb
<div class="small-3 columns">
  <h6><%= category.name %></h6>
  <% if  Transaction.find_by(appraisee: user, appraiser: current_user, category: category) %>
    <h4>Provided Already</h4>
  <% else %>
    <%= render 'form', user: user, category: category %>
  <% end %>
</div>

app/views/layouts/_head.html.erb
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title><%= content_for?(:title) ? yield(:title) : "Appraisal System" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">UserAppraisal</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <%if user_signed_in? %>
          <li><%= link_to  "My Appraisals", my_appraisals_path %></li>
          <li class="has-dropdown profile">
            <%= link_to current_user.email.split('@').first.capitalize, '#' %>
            <ul class="dropdown">
              <li> <%= link_to "Profile",edit_user_registration_path %></li>
              <li> <%= link_to "Logout",destroy_user_session_path, method: :delete%></li>
            </ul>
         </li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/_message.html.erb
<div class="row">
	<div class="small-12 columns">
		<% flash.each do |name, msg| %>
		  <% if msg.is_a?(String) && !msg.blank? %>
		    <div data-alert class="alert-box <%= name %>">
		      <%= content_tag :div, msg.html_safe, class: 'alert-msg' %>
		      <a href="#" class="close">&times;</a>
		    </div>
		  <% end %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>
  <body>
  	<%= render 'layouts/header' %>
  	<%= render 'layouts/message' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/user_appraisals/_form.html.erb
<%= form_with(model: UserAppraisal.new, local: true) do |form| %>
  <%= form.hidden_field :user_id, value: user.id %>
  <%= form.hidden_field :category_id, value: category.id %>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment%>
  </div>

  <div class="field">
    <%= form.label :points %>
    <%= form.number_field :points%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_appraisals/_user_appraisal.html.erb
Category:<%= user_appraisal.category.name %><br>
Comment:<%= user_appraisal.comment %><br>
Points: <%= user_appraisal.points %><br>

<hr>

app/views/user_appraisals/index.html.erb
<h1 align="center"> User Appraisals </h1>
<%= render @users%>

app/views/user_appraisals/my_appraisals.html.erb
<h1 align = "center">My Appraisals</h1>

<div class="row">
	<% @user_appraisals.each do |user_appraisal| %>
		<%= render user_appraisal %>
	<% end %>
</div>

app/views/user_appraisals/new.html.erb
<% render 'form'%>

app/views/user_appraisals/user_appraisal.html.erb
<h1 align = "center">User Appraisals</h1>
<div class="row">
	<% @user_appraisals.each do |user_appraisal| %>
		<div class="small -3 colums">
			<%= render user_appraisal %>
		</div>
	<% end %>
</div>

app/views/users/_user.html.erb
<% if (Transaction.where(appraisee: user, appraiser: current_user, category: @categories).count < 3 ) || current_user.points.positive? %>

<div class="row">
  <h5><%= current_user.manager ? (link_to user.email, "/user_appraisal/#{user.id}") : user.email  %><h5>
  <%= render @categories, user: user %>
</div>
<hr>
<% end %>